batch_size: 4
epoch: 200
learning_rate: 1e-3
gpu: 0
num_point: 2048
optimizer: Adam
weight_decay: 1e-4
lr_decay: 0.5
step_size: 20
num_category: 1
num_part: 4
num_workers: 8
train_episode: 600
output: ./save


model:
  nneighbor: 16 # knn
  nblocks: 4  # Unet层数
  transformer_dim: 512 # 输入维度
  name: PointTransformer

work_dir: log/PT/vegetableseg